sudo: false

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack

matrix:
  include:
  # - env: GHCVER=7.10.3 STACK_YAML=stack-7.10.yaml
  - env: GHCVER=7.10.3 CABALVER=1.22 STACK_CONFIG=/home/travis/build/alanz/HaRe/stack.yaml
    addons:
      apt:
        sources:
        - hvr-ghc
        - cassou-emacs
        packages:
        - libgmp-dev
        - cabal-install-1.22
        - happy-1.19.4
        - alex-3.1.3
        - ghc-7.10.3
        - emacs24
  # - env: GHCVER=head CABALVER=head STACK_CONFIG=stack-head.yaml
  #   addons:
  #     apt:
  #       sources:
  #       - hvr-ghc
  #       packages:
  #       - ghc-head
  # allow_failures:
  #   - env: GHCVER=head CABALVER=head STACK_CONFIG=stack-head.yaml

before_install:
  # Download and unpack the stack executable
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

  # ghc
  - export PATH=/opt/ghc/$GHCVER/bin:$PATH
  - export PATH=/opt/alex/3.1.3/bin:/opt/happy/1.19.4/bin:$PATH
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH

script:
  - cabal update
  - ./configure_tests.sh  # cabal configure the various test projects
  - ls -als
  - pwd
  - ./travis_long stack --stack-yaml $STACK_CONFIG --no-terminal --skip-ghc-check haddock --no-haddock-deps 
  - ./travis_long stack --stack-yaml $STACK_CONFIG --no-terminal --skip-ghc-check test
  - cabal check
  - cabal sdist   # tests that a source-distribution can be generated
  - emacs --version
  - emacs -Q --batch -L elisp -l elisp/tests/hare-tests.el -f ert-run-tests-batch-and-exit

notifications:
  irc: "irc.freenode.org#haskell-refactorer"

